name: commerception
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/animation1.json
    - assets/animation2.json
    - assets/animation3.json
    - assets/product1.png
    - assets/product2.jpg
    - assets/product3.png
    - assets/product4.png
